name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test memcached can run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Memcached setup
        uses: ./
        with:
            ports: "11211,11212,11213"
